message_file: "message.txt"
wg_gesucht_credentials:
  email: "my-email@email.com"
  password: "password1234"
url: ""
run_headless: false
min_listing_length_months: 6
attach_schufa: false
custom_condition: "user_name not in 'John Doe'"

# Optional (should work without these in most cases)
geckodriver_path: ""
firefox_path: ""